version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      # Group patch updates
      patch-updates:
        update-types:
          - "patch"
        patterns:
          - "*"

      # Group minor updates
      minor-updates:
        update-types:
          - "minor"
        patterns:
          - "*"

      # Group major updates (keep separate for careful review)
      major-updates:
        update-types:
          - "major"
        patterns:
          - "*"

    assignees:
      - "m1chael-pappas"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
